import { Link } from "react-router";
import { ArrowRight } from "lucide-react";
import { Button } from "~/components/ui/button";
import { APP_NAME } from "~/lib/constant";

// Assuming the type definitions are generated by the router dev tools
// import type { Route } from "./+types/_index";

export const meta = (/*{}: Route.MetaArgs*/) => {
  return [{ title: "Home" }, { name: "description", content: "Welcome to YourApp!" }];
};

export const action = async (/*{}: Route.ActionArgs*/) => {
  console.log("Home page action executed");
  return { ok: true };
};

export const clientAction = async (/*{}: Route.ClientActionArgs*/) => {
  console.log("Home page client action executed");
  return { ok: true };
};

export const loader = async (/*{}: Route.LoaderArgs*/) => {
  // Here you could fetch initial data for the landing page if needed
  return { pageLoadedAt: new Date().toISOString() };
};

export const clientLoader = async (/*{}: Route.ClientLoaderArgs*/) => {
  // Here you could fetch client-side specific data
  return { clientLoadedAt: new Date().toISOString() };
};

export const HydrateFallback = () => {
  // A simple fallback component shown during client-side hydration
  return <p>Loading Home Page...</p>;
};

export default function Index() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-background">
      <div className="absolute inset-0 -z-10 h-full w-full bg-background bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]"></div>

      <main className="container mx-auto flex flex-1 flex-col items-center justify-center p-4 text-center">
        <div className="max-w-3xl">
          <h1 className="bg-gradient-to-r from-primary via-blue-500 to-teal-500 bg-clip-text text-5xl font-bold tracking-tighter text-transparent md:text-7xl">
            Build and Deploy with Confidence
          </h1>

          <p className="mx-auto mt-6 max-w-xl text-lg text-muted-foreground md:text-xl">
            You've set up a powerful, modern, and scalable foundation for your next big idea. Let's get
            started.
          </p>

          <div className="mt-8 flex justify-center">
            <Button asChild size="lg" className="gap-2">
              <Link to="/login">
                <span>Get Started</span>
                <ArrowRight className="size-4" />
              </Link>
            </Button>
          </div>
        </div>
      </main>

      <footer className="py-8 text-sm text-muted-foreground">
        <p>
          &copy; {new Date().getFullYear()} {APP_NAME} Inc. All Rights Reserved.
        </p>
      </footer>
    </div>
  );
}
